<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    public function run()
    {
        $permissions = [
            [
                'id' => 1,
                'title' => 'user_management_access',
                'perm_type' => 5,
                'grp_title' => 'User management',
              ],
              [
                'id' => 2,
                'title' => 'permission_create',
                'perm_type' => 1,
                'grp_title' => 'Permissions',
              ],
              [
                'id' => 3,
                'title' => 'permission_edit',
                'perm_type' => 2,
                'grp_title' => 'Permissions',
              ],
              [
                'id' => 4,
                'title' => 'permission_show',
                'perm_type' => 3,
                'grp_title' => 'Permissions',
              ],
              [
                'id' => 5,
                'title' => 'permission_delete',
                'perm_type' => 4,
                'grp_title' => 'Permissions',
              ],
              [
                'id' => 6,
                'title' => 'permission_access',
                'perm_type' => 5,
                'grp_title' => 'Permissions',
              ],
              [
                'id' => 7,
                'title' => 'role_create',
                'perm_type' => 1,
                'grp_title' => 'Roles',
              ],
              [
                'id' => 8,
                'title' => 'role_edit',
                'perm_type' => 2,
                'grp_title' => 'Roles',
              ],
              [
                'id' => 9,
                'title' => 'role_show',
                'perm_type' => 3,
                'grp_title' => 'Roles',
              ],
              [
                'id' => 10,
                'title' => 'role_delete',
                'perm_type' => 4,
                'grp_title' => 'Roles',
              ],
              [
                'id' => 11,
                'title' => 'role_access',
                'perm_type' => 5,
                'grp_title' => 'Roles',
              ],
              [
                'id' => 12,
                'title' => 'user_create',
                'perm_type' => 1,
                'grp_title' => 'Users',
              ],
              [
                'id' => 13,
                'title' => 'user_edit',
                'perm_type' => 2,
                'grp_title' => 'Users',
              ],
              [
                'id' => 14,
                'title' => 'user_show',
                'perm_type' => 3,
                'grp_title' => 'Users',
              ],
              [
                'id' => 15,
                'title' => 'user_delete',
                'perm_type' => 4,
                'grp_title' => 'Users',
              ],
              [
                'id' => 16,
                'title' => 'user_access',
                'perm_type' => 5,
                'grp_title' => 'Users',
              ],
              [
                'id' => 17,
                'title' => 'audit_log_show',
                'perm_type' => 3,
                'grp_title' => 'Audit Logs',
              ],
              [
                'id' => 18,
                'title' => 'audit_log_access',
                'perm_type' => 5,
                'grp_title' => 'Audit Logs',
              ],
              [
                'id' => 19,
                'title' => 'profile_password_edit',
                'perm_type' => 2,
                'grp_title' => 'Profile',
              ],
              [
                'id' => 20,
                'title' => 'dashboard_access',
                'perm_type' => 5,
                'grp_title' => 'Dashboard',
              ],
              [
                'id' => 21,
                'title' => 'landing_access',
                'perm_type' => 5,
                'grp_title' => 'Landing',
              ],
              [
                'id' => 22,
                'title' => 'dashboardv_access',
                'perm_type' => 5,
                'grp_title' => 'Dashboard Verifikator',
              ],
              [
                'id' => 23,
                'title' => 'dashboarda_access',
                'perm_type' => 5,
                'grp_title' => 'Dashboard Admin',
              ],
              [
                'id' => 24,
                'title' => 'user_task_access',
                'perm_type' => 5,
                'grp_title' => 'Proses RIPH',
              ],
              [
                'id' => 25,
                'title' => 'pull_access',
                'perm_type' => 5,
                'grp_title' => 'Tarik Data RIPH',
              ],
              [
                'id' => 26,
                'title' => 'commitment_access',
                'perm_type' => 5,
                'grp_title' => 'Daftar RIPH',
              ],
              [
                'id' => 27,
                'title' => 'kelompoktani_access',
                'perm_type' => 5,
                'grp_title' => 'Kelompok Tani',
              ],
              [
                'id' => 28,
                'title' => 'permohonan_access',
                'perm_type' => 5,
                'grp_title' => 'Permohonan',
              ],
              [
                'id' => 29,
                'title' => 'pengajuan_access',
                'perm_type' => 5,
                'grp_title' => 'Pengajuan Verifikasi',
              ],
              [
                'id' => 30,
                'title' => 'pengajuan_create',
                'perm_type' => 1,
                'grp_title' => 'Pengajuan Verifikasi',
              ],
              [
                'id' => 31,
                'title' => 'pengajuan_edit',
                'perm_type' => 2,
                'grp_title' => 'Pengajuan Verifikasi',
              ],
              [
                'id' => 32,
                'title' => 'pengajuan_show',
                'perm_type' => 3,
                'grp_title' => 'Pengajuan Verifikasi',
              ],
              [
                'id' => 33,
                'title' => 'pengajuan_delete',
                'perm_type' => 4,
                'grp_title' => 'Pengajuan Verifikasi',
              ],
              [
                'id' => 34,
                'title' => 'skl_access',
                'perm_type' => 5,
                'grp_title' => 'SKL Terbit',
              ],
              [
                'id' => 35,
                'title' => 'skl_create',
                'perm_type' => 1,
                'grp_title' => 'Daftar SKL',
              ],
              [
                'id' => 36,
                'title' => 'skl_edit',
                'perm_type' => 2,
                'grp_title' => 'Daftar SKL',
              ],
              [
                'id' => 37,
                'title' => 'skl_show',
                'perm_type' => 3,
                'grp_title' => 'Daftar SKL',
              ],
              [
                'id' => 38,
                'title' => 'skl_delete',
                'perm_type' => 4,
                'grp_title' => 'Daftar SKL',
              ],
              [
                'id' => 39,
                'title' => 'folder_access',
                'perm_type' => 5,
                'grp_title' => 'Pengelolaan Berkas',
              ],
              [
                'id' => 40,
                'title' => 'berkas_access',
                'perm_type' => 5,
                'grp_title' => 'Berkas Saya',
              ],
              [
                'id' => 41,
                'title' => 'galeri_access',
                'perm_type' => 5,
                'grp_title' => 'Galeri Saya',
              ],
              [
                'id' => 42,
                'title' => 'template_access',
                'perm_type' => 5,
                'grp_title' => 'Template Master',
              ],
              [
                'id' => 43,
                'title' => 'onfarm_access',
                'perm_type' => 5,
                'grp_title' => 'Onfarm',
              ],
              [
                'id' => 44,
                'title' => 'online_access',
                'perm_type' => 5,
                'grp_title' => 'Online',
              ],
              [
                'id' => 45,
                'title' => 'completed_access',
                'perm_type' => 5,
                'grp_title' => 'Completed',
              ],
              [
                'id' => 46,
                'title' => 'verificator_task_access',
                'perm_type' => 5,
                'grp_title' => 'Verificator task',
              ],
              [
                'id' => 47,
                'title' => 'feedmsg_access',
                'perm_type' => 5,
                'grp_title' => 'Feed & Messages',
              ],
              [
                'id' => 48,
                'title' => 'feeds_access',
                'perm_type' => 5,
                'grp_title' => 'Feeds',
              ],
              [
                'id' => 49,
                'title' => 'feeds_create',
                'perm_type' => 1,
                'grp_title' => 'Feeds',
              ],
              [
                'id' => 50,
                'title' => 'feeds_edit',
                'perm_type' => 2,
                'grp_title' => 'Feeds',
              ],
              [
                'id' => 51,
                'title' => 'feeds_show',
                'perm_type' => 3,
                'grp_title' => 'Feeds',
              ],
              [
                'id' => 52,
                'title' => 'feeds_delete',
                'perm_type' => 4,
                'grp_title' => 'Feeds',
              ],
              [
                'id' => 53,
                'title' => 'messenger_access',
                'perm_type' => 5,
                'grp_title' => 'Messenger',
              ],
              [
                'id' => 54,
                'title' => 'messenger_create',
                'perm_type' => 1,
                'grp_title' => 'Messenger',
              ],
              [
                'id' => 55,
                'title' => 'messenger_edit',
                'perm_type' => 2,
                'grp_title' => 'Messenger',
              ],
              [
                'id' => 56,
                'title' => 'messenger_show',
                'perm_type' => 3,
                'grp_title' => 'Messenger',
              ],
              [
                'id' => 57,
                'title' => 'messenger_delete',
                'perm_type' => 4,
                'grp_title' => 'Messenger',
              ],
              [
                'id' => 58,
                'title' => 'verification_skl_access',
                'perm_type' => 5,
                'grp_title' => 'Verificator SKL',
              ],
              [
                'id' => 59,
                'title' => 'list_skl_access',
                'perm_type' => 5,
                'grp_title' => 'SKL List',
              ],
              [
                'id' => 60,
                'title' => 'list_skl_create',
                'perm_type' => 1,
                'grp_title' => 'SKL List',
              ],
              [
                'id' => 61,
                'title' => 'list_skl_edit',
                'perm_type' => 2,
                'grp_title' => 'SKL List',
              ],
              [
                'id' => 62,
                'title' => 'list_skl_show',
                'perm_type' => 3,
                'grp_title' => 'SKL List',
              ],
              [
                'id' => 63,
                'title' => 'list_skl_delete',
                'perm_type' => 4,
                'grp_title' => 'SKL List',
              ],
              [
                'id' => 64,
                'title' => 'create_skl_access',
                'perm_type' => 5,
                'grp_title' => 'Create SKL',
              ],
              [
                'id' => 65,
                'title' => 'issued_skl_access',
                'perm_type' => 5,
                'grp_title' => 'Issued SKL',
              ],
              [
                'id' => 66,
                'title' => 'administrator_access',
                'perm_type' => 5,
                'grp_title' => 'Administrator',
              ],
              [
                'id' => 67,
                'title' => 'create_skl_create',
                'perm_type' => 1,
                'grp_title' => 'Create SKL',
              ],
              [
                'id' => 68,
                'title' => 'create_skl_edit',
                'perm_type' => 2,
                'grp_title' => 'Create SKL',
              ],
              [
                'id' => 69,
                'title' => 'create_skl_show',
                'perm_type' => 3,
                'grp_title' => 'Create SKL',
              ],
              [
                'id' => 70,
                'title' => 'create_skl_delete',
                'perm_type' => 4,
                'grp_title' => 'Create SKL',
              ],
              [
                'id' => 71,
                'title' => 'issued_skl_create',
                'perm_type' => 1,
                'grp_title' => 'Issued SKL',
              ],
              [
                'id' => 72,
                'title' => 'issued_skl_edit',
                'perm_type' => 2,
                'grp_title' => 'Issued SKL',
              ],
              [
                'id' => 73,
                'title' => 'issued_skl_show',
                'perm_type' => 3,
                'grp_title' => 'Issued SKL',
              ],
              [
                'id' => 74,
                'title' => 'issued_skl_delete',
                'perm_type' => 4,
                'grp_title' => 'Issued SKL',
              ],
              [
                'id' => 75,
                'title' => 'master_riph_access',
                'perm_type' => 5,
                'grp_title' => 'Master Data RIPH',
              ],
              [
                'id' => 76,
                'title' => 'data_report_access',
                'perm_type' => 5,
                'grp_title' => 'Data Report',
              ],
              [
                'id' => 77,
                'title' => 'master_template_access',
                'perm_type' => 5,
                'grp_title' => 'Master Template',
              ],
              [
                'id' => 78,
                'title' => 'commitment_list_access',
                'perm_type' => 5,
                'grp_title' => 'Commitment List',
              ],
              [
                'id' => 79,
                'title' => 'verification_report_access',
                'perm_type' => 5,
                'grp_title' => 'Verification Report',
              ],
              [
                'id' => 80,
                'title' => 'verif_onfarm_access',
                'perm_type' => 5,
                'grp_title' => 'Onfarm Report',
              ],
              [
                'id' => 81,
                'title' => 'verif_online_access',
                'perm_type' => 5,
                'grp_title' => 'Online Report',
              ],
              [
                'id' => 82,
                'title' => 'admin_SKL_access',
                'perm_type' => 5,
                'grp_title' => 'SKL',
              ],
              [
                'id' => 83,
                'title' => 'master_riph_edit',
                'perm_type' => 2,
                'grp_title' => 'Master Data RIPH',
              ],
              [
                'id' => 84,
                'title' => 'master_riph_create',
                'perm_type' => 1,
                'grp_title' => 'Master Data RIPH',
              ],
              [
                'id' => 85,
                'title' => 'master_riph_show',
                'perm_type' => 3,
                'grp_title' => 'Master Data RIPH',
              ],
              [
                'id' => 86,
                'title' => 'master_riph_delete',
                'perm_type' => 4,
                'grp_title' => 'Master Data RIPH',
              ],
              [
                'id' => 87,
                'title' => 'commitment_create',
                'perm_type' => 1,
                'grp_title' => 'Commitment',
              ],
              [
                'id' => 88,
                'title' => 'commitment_edit',
                'perm_type' => 2,
                'grp_title' => 'Daftar RIPH',
              ],
              [
                'id' => 89,
                'title' => 'commitment_delete',
                'perm_type' => 4,
                'grp_title' => 'Daftar RIPH',
              ],
              [
                'id' => 90,
                'title' => 'commitment_show',
                'perm_type' => 3,
                'grp_title' => 'Daftar RIPH',
              ],
              [
                'id' => 91,
                'title' => 'hello_edit',
                'perm_type' => 2,
                'grp_title' => 'Data Report',
              ],
              [
                'id' => 92,
                'title' => 'provinsi_access',
                'perm_type' => 5,
                'grp_title' => 'Provinsi',
              ],
              [
                'id' => 93,
                'title' => 'kabupaten_access',
                'perm_type' => 5,
                'grp_title' => 'Kabupaten',
              ],
              [
                'id' => 94,
                'title' => 'kecamatan_access',
                'perm_type' => 5,
                'grp_title' => 'Kecamatan',
              ],
              [
                'id' => 95,
                'title' => 'desa_access',
                'perm_type' => 5,
                'grp_title' => 'Desa',
              ],
              [
                'id' => 96,
                'title' => 'master_wilayah_access',
                'perm_type' => 5,
                'grp_title' => 'Master Wilayah',
              ],
              [
                'id' => 97,
                'title' => 'poktan_create',
                'perm_type' => 1,
                'grp_title' => 'Daftar Kelompok Tani',
              ],
              [
                'id' => 98,
                'title' => 'poktan_edit',
                'perm_type' => 2,
                'grp_title' => 'Daftar Kelompok Tani',
              ],
              [
                'id' => 99,
                'title' => 'poktan_show',
                'perm_type' => 3,
                'grp_title' => 'Daftar Kelompok Tani',
              ],
              [
                'id' => 100,
                'title' => 'poktan_delete',
                'perm_type' => 4,
                'grp_title' => 'Daftar Kelompok Tani',
              ],
              [
                'id' => 101,
                'title' => 'daftar_riph_create',
                'perm_type' => 1,
                'grp_title' => 'Daftar RIPH',
              ],
              [
                'id' => 102,
                'title' => 'pks_access',
                'perm_type' => 5,
                'grp_title' => 'Daftar PKS',
              ],
              [
                'id' => 103,
                'title' => 'poktan_access',
                'perm_type' => 5,
                'grp_title' => 'Daftar Kelompok Tani',
              ],
              [
                'id' => 104,
                'title' => 'pks_create',
                'perm_type' => 1,
                'grp_title' => 'Daftar PKS',
              ],
              [
                'id' => 105,
                'title' => 'pks_edit',
                'perm_type' => 2,
                'grp_title' => 'Daftar PKS',
              ],
              [
                'id' => 106,
                'title' => 'pks_show',
                'perm_type' => 3,
                'grp_title' => 'Daftar PKS',
              ],
              [
                'id' => 107,
                'title' => 'pks_delete',
                'perm_type' => 4,
                'grp_title' => 'Daftar PKS',
              ],
              [
                'id' => 108,
                'title' => 'v2access',
                'perm_type' => '6',
                'grp_title' => 'V2 User',
              ],
              [
                'id' => 109,
                'title' => 'varietas_access',
                'perm_type' => 5,
                'grp_title' => 'Varietas',
              ],
              [
                'id' => 110,
                'title' => 'varietas_create',
                'perm_type' => 1,
                'grp_title' => 'Varietas',
              ],
              [
                'id' => 111,
                'title' => 'varietas_show',
                'perm_type' => 3,
                'grp_title' => 'Varietas',
              ],
              [
                'id' => 112,
                'title' => 'varietas_edit',
                'perm_type' => 2,
                'grp_title' => 'Varietas',
              ],
              [
                'id' => 113,
                'title' => 'varietas_delete',
                'perm_type' => 4,
                'grp_title' => 'Varietas',
              ],
              [
                'id' => 114,
                'title' => 'old_skl_access',
                'perm_type' => 5,
                'grp_title' => 'Old Skl',
              ],
              [
                'id' => 115,
                'title' => 'old_skl_create',
                'perm_type' => 1,
                'grp_title' => 'Old Skl',
              ],
              [
                'id' => 116,
                'title' => 'old_skl_edit',
                'perm_type' => 2,
                'grp_title' => 'Old Skl',
              ],
              [
                'id' => 117,
                'title' => 'old_skl_show',
                'perm_type' => 3,
                'grp_title' => 'Old Skl',
              ],
              [
                'id' => 118,
                'title' => 'old_skl_delete',
                'perm_type' => 4,
                'grp_title' => 'Old Skl',
              ]
        ];

        Permission::insert($permissions);
    }
}
